

services:
  # The Node.js application service
  app:
    build: .
    container_name: product-catalog-api
    ports:
      - "3000:3000"  # Exposing app on host:3000
    environment:
      - NODE_ENV=development
      - DB_HOST=db  # Host name of the Postgres container
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=product_catalog
    depends_on:
      - db  # Ensure the db service starts first
    volumes:
      - .:/app  # Mount current directory into /app in the container
    command: ["npm", "start"]  # Start your app with npm

  # The PostgreSQL database service
  db:
    image: postgres:13
    container_name: product-catalog-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product_catalog
    ports:
      - "5433:5432"  
    volumes:
      - product_catalog_data:/var/lib/postgresql/data  

# Volumes to persist data between restarts
volumes:
  product_catalog_data:
