openapi: 3.0.3
info:
  title: Product Catalog API
  version: 1.0.0
  description: API for managing product catalog.

paths:
  /api/products/create:
    post:
      summary: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - price
                - stock
              properties:
                name:
                  type: string
                  example: ProductMe
                price:
                  type: number
                  format: float
                  example: 4000
                stock:
                  type: integer
                  example: 8999
      responses:
        '200':
          description: Product created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      product:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 6
                          name:
                            type: string
                            example: ProductMe
                          price:
                            type: string
                            example: "4000.00"
                          stock:
                            type: integer
                            example: 8999
                          created_at:
                            type: string
                            format: date-time
                            example: "2025-04-23T10:33:46.170Z"
                          updated_at:
                            type: string
                            format: date-time
                            example: "2025-04-23T10:33:46.170Z"
                          deleted_at:
                            type: string
                            nullable: true
                            example: null

  /api/products/:
    get:
      summary: Get all products
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      products:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 7
                            name:
                              type: string
                              example: ProductMe
                            price:
                              type: string
                              example: "4000.00"
                            stock:
                              type: integer
                              example: 788
                            created_at:
                              type: string
                              format: date-time
                              example: "2025-04-23T10:44:29.275Z"
                            updated_at:
                              type: string
                              format: date-time
                              example: "2025-04-23T10:44:29.275Z"
                            deleted_at:
                              type: string
                              nullable: true
                              example: null

  /api/products/{id}:
    put:
      summary: Update a product by ID
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the product to update
          schema:
            type: integer
            example: 6
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - price
                - stock
              properties:
                name:
                  type: string
                  example: ProductYouandme
                price:
                  type: number
                  format: float
                  example: 9000000
                stock:
                  type: integer
                  example: 788
      responses:
        '200':
          description: Product updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      product:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 6
                          name:
                            type: string
                            example: ProductYouandme
                          price:
                            type: string
                            example: "9000000.00"
                          stock:
                            type: integer
                            example: 788
                          created_at:
                            type: string
                            format: date-time
                            example: "2025-04-23T10:33:46.170Z"
                          updated_at:
                            type: string
                            format: date-time
                            example: "2025-04-23T10:35:14.171Z"
                          deleted_at:
                            type: string
                            nullable: true
                            example: null
    delete:
      summary: Delete a product by ID
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the product to delete
          schema:
            type: integer
            example: 6
      responses:
        '200':
          description: Product deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Product deleted successfully
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
  /api/products/search/:
    post:
      summary: Search products by name
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  example: ProductMe
      responses:
        '200':
          description: A list of products matching the search
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      products:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 9
                            name:
                              type: string
                              example: ProductMe
                            price:
                              type: string
                              example: "4000.00"
                            stock:
                              type: integer
                              example: 8999
                            created_at:
                              type: string
                              format: date-time
                              example: "2025-04-23T10:52:53.320Z"
                            updated_at:
                              type: string
                              format: date-time
                              example: "2025-04-23T10:52:53.320Z"
                            deleted_at:
                              type: string
                              nullable: true
                              example: null
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: fail
                  message:
                    type : string
                    example : Product not found
