name: Test and Deploy Product Catalog API

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Build and Test Containers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker containers
        run: docker compose -f docker-compose.yml up -d --build

      - name: Run Tests
        run: |
          docker compose exec app npm test || true
          docker compose down

  deploy:
    name: Deploy to EC2 Server
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy with SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            echo "💥 Removing old project"
            rm -rf product-catalog-api

            echo " Cloning latest version"
            git clone https://github.com/olugben/product-catalog.git

            cd product-catalog

            echo "🔄 Restarting containers"
            docker compose down
            docker compose up -d --build

            echo "🧹 Cleaning up Docker"
            docker system prune -af

            echo "✅ Deployment complete"
